# This is a basic workflow to help you get started with Actions

name: Build-package-containerize-upload-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
      - requested
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
#     - uses: actions/checkout@v3
      - name: package springboot app
        run: mvn package
      - name: build container and deploy
        run: docker-compose up -d
      - name: push container to docker hub 
        run: docker push noizebomb/springboot-app-2:1.0.4
